site_name: Lynn's Blog
site_url: https://lynnxie00.github.io/LynnBlog/
theme:
    name: simple-blog

# Extensions
markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2
