site_name: Lynn's Blog
site_url: https://lynnxie00.github.io/LynnBlog/
nav:
    - Home: index.md
theme:
    name: simple-blog

# Extensions
markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
